version: "3.2"

services:
  web:
    container_name: image_host
    env_file: .env
    build:
      context: .
      args:
        - MYSQL_PWD=$MYSQL_PWD
    restart: always
    ports:
      - 8080:80
    environment:
        - ASPNETCORE_MYSQL_PWD=${MYSQL_PWD}