version: "3.4"

services:
  web:
    container_name: image_host
    env_file: .env
    build:
      context: .
      args:
        - MYSQL_PWD=$MYSQL_PWD
      network: innernetwork
    restart: always
    ports:
      - 3010:80
    environment:
        - ASPNETCORE_MYSQL_PWD=${MYSQL_PWD}
    volumes:
      - aws_config:/root/.aws

networks:
  default:
    external:
      name: innernetwork

volumes:
  aws_config: