version: "3.2"

services:
  web:
    build:
      context: .
    restart: always
    ports:
    - 8080:80
    volumes:
    - .development.db:/app/development.db
    - .production.db:/app/production.db
